---
- name: Install Postgres Repo
  yum: name={{ postgres_repo_url }} state=present
  register: result
  retries: 10
  until: result.rc == 0
  delay: 5
  become: yes

- name: Install Postgres Server
  yum: 
    name: "{{ postgres_server }}"
    state: present
  become: yes
  
- name: Install postgresql-contrib 
  yum: 
    name: postgresql11-contrib 
    state: present
  become: yes  

- name: Checking Postgres config file "::" {{ postgres_config_file }}
  stat: 
    path: "{{ postgres_config_file }}"
  register: postgres_config_file_created
  become: yes

- name: Creating database
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  when: postgres_config_file_created.stat.exists == false
  become: yes

- name: Rendering {{ postgres_config_file }}
  template: 
    src: "{{ item }}.j2" 
    dest: "{{ postgres_config_file }}" 
    owner: postgres 
    group: postgres 
    mode: 0640
  with_items:
    - postgresql.conf
  become: yes

- name: Rendering {{ postgres_hba_file }}
  template: 
    src: "{{ item }}.j2"
    dest: "{{ postgres_hba_file }}"
    owner: postgres 
    group: postgres 
    mode: 0644
  with_items:
    - pg_hba.conf
  become: yes

- name: Adding libs required for Postgres + Ansible (python-passlib)
  yum: 
    name: python-passlib 
    state: present
  become: yes

- name: Adding libs required for Postgres + Ansible (python-psycopg2)
  yum: 
    name: python-psycopg2 
    state: present
  become: yes

- name: Starting up {{ postgres_service }}
  service: 
    name: "{{ postgres_service }}"
    state: started 
    enabled: yes
  ignore_errors: yes
  become: yes

- name: Adding sa
  postgresql_user: 
    name: 'sa'
    password: 'Kiscirmos123.'
    role_attr_flags: 'SUPERUSER,LOGIN'
  become_user: postgres
  become: yes

- name: Restarting {{ postgres_service }}
  service: 
    name: "{{ postgres_service }}" 
    state: reloaded
  become: yes
